### ISSUE TITLE
"More" categories in alphabetic order

### ISSUE THREAD

**Issue by andreanidouglas** [liyasthomas/books#1]
**Is your feature request related to a problem? Please describe.**
Easier to go through the list and find the one we are searching.

**Describe the solution you'd like**
Sort the `More` list with genres in alphabetic order.

**Comment by liyasthomas** [comment]
Issue has been identified. Will be resolved in next commit.

**Comment by liyasthomas** [comment]
✨ Alphabetically order more categories
🐛 Fixes #1
