### ISSUE TITLE
Undefined in the books container instead of the books or the previous ones

### ISSUE THREAD

**Issue by hasan-sh** [liyasthomas/books#3]
**Describe the bug**
`undefined` or an array of objects instead of the books!

**To Reproduce**
1. Go to https://liyasthomas.github.io/books/
2. Scroll down to `Bestsellers`
3. Click on the right arrow

**Expected behavior**
More books, or the previous fetched books!

**Screenshots**
![bug](https://user-images.githubusercontent.com/20051470/63647244-735e0a80-c71e-11e9-9df8-e830671148f9.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by liyasthomas** [comment]
Please give an explanation for your issue

**Comment by hasan-sh** [comment]
> Please give an explanation for your issue

Sorry, for some reason everything I wrote, was deleted!!

**Comment by liyasthomas** [comment]
Issue has been identified. Will look into it and let you know the progress. Thanks for your concern.
